<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TrangPC" name="testRnC.TestRnC01" tests="28" failures="26" timestamp="15 May 2016 04:31:21 GMT" time="1279.153" errors="0">
  <testcase name="test_sachmem" time="47.663" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014855369?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014855369?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="44.179" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014720267?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014720267?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="50.731" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014363404?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014363404?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="49.600" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939015367198?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939015367198?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="38.902" classname="testRnC.TestRnC01"/>
  <testcase name="test_sachmem" time="43.759" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939015124615?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939015124615?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="44.795" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014545265?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014545265?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="46.700" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939015032195?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939015032195?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="44.491" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014898167?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014898167?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="44.691" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014988334?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014988334?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="43.502" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014501417?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014501417?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="45.408" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014457508?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014457508?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="46.933" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014143586?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014143586?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="45.176" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939015079769?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939015079769?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="45.169" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014764835?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014764835?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="43.489" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014317643?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014317643?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="43.521" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014588870?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014588870?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="47.755" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939015218087?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939015218087?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="46.311" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014810281?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014810281?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="39.002" classname="testRnC.TestRnC01"/>
  <testcase name="test_sachmem" time="48.109" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939015170838?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939015170838?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="45.679" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014274192?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014274192?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="44.413" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014943429?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014943429?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="42.886" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014632444?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014632444?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="52.049" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014408485?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014408485?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="57.190" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939015311094?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939015311094?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="42.913" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939015265910?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939015265910?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="44.137" classname="testRnC.TestRnC01">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete.01 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939014676794?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete.01 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939014676794?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC01.test_sachmem(TestRnC01.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
</testsuite> <!-- testRnC.TestRnC01 -->
