<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TrangPC" name="testRnC.TestRnC" tests="16" failures="14" timestamp="14 May 2016 07:34:13 GMT" time="857.854" errors="0">
  <testcase name="test_sachmem" time="49.370" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939089951695?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939089951695?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="24.834" classname="testRnC.TestRnC"/>
  <testcase name="test_sachmem" time="43.832" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939090239196?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939090239196?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="49.773" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939090337352?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939090337352?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="107.979" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939090048524?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939090048524?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="70.551" classname="testRnC.TestRnC"/>
  <testcase name="test_sachmem" time="44.076" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939090287593?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939090287593?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="50.496" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939089903078?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939089903078?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="67.165" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939089716004?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939089716004?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="44.772" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939089571743?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939089571743?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="46.232" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939090160239?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939090160239?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="46.425" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939090381234?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939090381234?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="51.175" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939089857738?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939089857738?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="51.121" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939089617431?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939089617431?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="56.178" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939089664267?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939089664267?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
  <testcase name="test_sachmem" time="53.875" classname="testRnC.TestRnC">
    <failure type="com.applitools.eyes.TestFailedException" message="&#039;Read and Complete 3,4 01&#039; of &#039;Sachmem&#039;. See details at https://eyes.applitools.com/app/sessions/251939089995130?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~">
      <![CDATA[com.applitools.eyes.TestFailedException: 'Read and Complete 3,4 01' of 'Sachmem'. See details at https://eyes.applitools.com/app/sessions/251939089995130?accountId=Q0X2BIVd5E_VSsNUq7ZQhw~~
	at com.applitools.eyes.EyesBase.close(EyesBase.java:600)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:540)
	at com.applitools.eyes.Eyes.close(Eyes.java:17)
	at testRnC.TestRnC.test_sachmem(TestRnC.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- test_sachmem -->
</testsuite> <!-- testRnC.TestRnC -->
